version: 0.2
phases:
  install:
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - echo "Installing something"
  build:
    commands:
      - echo Build started on `date`
      - echo Installing composer deps
      - composer install

  post_build:
    commands:
      - echo Build completed on `date`
